version: '3.7'

x-common: &common
  build: .
  ports:
      - "8000:8000"


# Services not meant to be started all at once
# see the run_test.py for details

services:
  flask_marshmallow_gunicorn:
    <<: *common
    working_dir: /app_flask_marshmallow
    command: gunicorn main:app --bind 0.0.0.0:8000 --workers ${WORKERS}
  
  drf_gunicorn:
    <<: *common
    working_dir: /app_drf
    command: gunicorn drf.wsgi:application --bind 0.0.0.0:8000 --workers ${WORKERS}

  drf_gunicorn_gevent:
    <<: *common
    working_dir: /app_drf
    command: gunicorn drf.wsgi:application --worker-class gevent --bind 0.0.0.0:8000 --workers ${WORKERS}

  ninja_gunicorn:
    <<: *common
    working_dir: /app_ninja
    command: gunicorn djninja.wsgi:application --bind 0.0.0.0:8000 --workers ${WORKERS}

  ninja_gunicorn_gevent:
    <<: *common
    working_dir: /app_ninja
    command: gunicorn djninja.wsgi:application --worker-class gevent --bind 0.0.0.0:8000 --workers ${WORKERS}

  ninja_gunicorn_uvcorn:
    <<: *common
    working_dir: /app_ninja
    command: gunicorn djninja.asgi:application --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers ${WORKERS}

  ninja_uvicorn:
    <<: *common
    working_dir: /app_ninja
    command: uvicorn djninja.asgi:application --host 0.0.0.0 --workers ${WORKERS}

  fastapi_gunicorn:
    <<: *common
    working_dir: /app_fastapi
    command: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers ${WORKERS}

  fastapi_uvicorn:
    <<: *common
    working_dir: /app_fastapi
    command: uvicorn main:app --host 0.0.0.0 --workers ${WORKERS}

  network_service:
    build: .
    command: python network_service.py > /dev/null
